import { relations } from 'drizzle-orm';
import { pgTable, text, boolean, timestamp, uuid, jsonb } from 'drizzle-orm/pg-core';
import { user } from './auth-schema.js';

export const posts = pgTable('posts', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  slug: text('slug').notNull().unique(),
  body: text('body'),
  status: text('status').notNull().default('draft'),
  published: boolean('published').notNull().default(false),
  authorId: text('author_id').references(() => user.id),
  // repeater state: an array of rows, hence jsonb rather than a side table
  links: jsonb('links'),
  // file upload stores the path, never the bytes
  cover: text('cover'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const comments = pgTable('comments', {
  id: uuid('id').primaryKey().defaultRandom(),
  postId: uuid('post_id')
    .notNull()
    .references(() => posts.id, { onDelete: 'cascade' }),
  author: text('author').notNull(),
  body: text('body').notNull(),
  approved: boolean('approved').notNull().default(false),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const postsRelations = relations(posts, ({ one, many }) => ({
  author: one(user, { fields: [posts.authorId], references: [user.id] }),
  comments: many(comments),
}));

export const commentsRelations = relations(comments, ({ one }) => ({
  post: one(posts, { fields: [comments.postId], references: [posts.id] }),
}));

// Auth tables (user, session, account, verification) are re-exported below
// once generated by the better-auth CLI.
export * from './auth-schema.js';
