import { pgTable, text, boolean, timestamp, uuid } from 'drizzle-orm/pg-core';

export const posts = pgTable('posts', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  slug: text('slug').notNull().unique(),
  body: text('body'),
  status: text('status').notNull().default('draft'),
  published: boolean('published').notNull().default(false),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

// Auth tables (user, session, account, verification) are re-exported below
// once generated by the better-auth CLI.
export * from './auth-schema.js';
