import { relations } from 'drizzle-orm';
import { pgTable, text, boolean, timestamp, uuid } from 'drizzle-orm/pg-core';
import { user } from './auth-schema.js';

export const posts = pgTable('posts', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  slug: text('slug').notNull().unique(),
  body: text('body'),
  status: text('status').notNull().default('draft'),
  published: boolean('published').notNull().default(false),
  authorId: text('author_id').references(() => user.id),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const postsRelations = relations(posts, ({ one }) => ({
  author: one(user, { fields: [posts.authorId], references: [user.id] }),
}));

// Auth tables (user, session, account, verification) are re-exported below
// once generated by the better-auth CLI.
export * from './auth-schema.js';
